config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  get '/searches/search' => 'searches#search',as: 'searches'
  get '/searches/categorysearch' => 'searches#categorysearch'

  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do

    resources :reviews, only: [:create]
    resources :book_comments, only: [:create,:destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      get 'join' => 'groups#join'
      get 'out' => 'groups#out'
      get 'contact' => 'groups#contact'
      post 'contact' => 'groups#contact_create'

    end
    get :followings, on: :member
    get :followers,on: :member
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image_id
  has_many :group_users, dependent: :destroy

  validates :name,presence: true,uniqueness: true
  validates :introduction, length: {maximum: 140}



  def get_image_id(size)
    unless image_id.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image_id.attach(io: File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image_id.variant(resize: size).processed
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :correct,only: [:edit,:update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id

    if @group.save
      @group_user = current_user.group_users.create(group_id: @group.id)
      redirect_to user_groups_path
    else
      render :new
    end
  end

  def join
    @group_user = current_user.group_users.create(group_id: params[:group_id])
    redirect_to user_groups_path
  end

  def out
    @group_user = GroupUser.find_by(user_id: params[:user_id],group_id: params[:group_id])
    @group_user.destroy
    redirect_to user_groups_path
  end

  def contact
    @user = User.find(params[:user_id])
    @group = Group.find(params[:group_id])
    @users = @group.group_users
  end

  def contact_create
    @group = Group.find(params[:group_id])
    @users = @group.group_users
    @contact = params[:contact]
    @title = params[:title]

    if @title.length == 0 or @contact.length == 0
      flash[:notice]= "送信失敗"
      render :contact
    end

    @users.each do |user_id|
      @user = user_id.user
      ContactMailer.send_mail(@user,@contact,@title).deliver_now
    end


  end





  def index
    @book = Book.new
    @groups = Group.all
    @group_user = GroupUser.all

  end

  def show
    @group = Group.find(params[:id])
    @book_new =Book.new
    if GroupUser.find_by(user_id: current_user, group_id: @group.id).present?
      @isgroup = true
    else
      @isgroup = false
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to user_group_path(current_user.id,@group.id)
    else
      render :edit
    end
  end

  def destroy

  end

  private


  def group_params
    params.require(:group).permit(:name, :introduction, :image_id,)
  end

  def correct
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to users_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_aftersend.html.erb
<h2>送信完了しました。</h2>
<p>内容は以下の通りです</p>

<P>[タイトル]</P>
<%= @title %>
<P>[本文]</P>
<%= @contact %>

app/views/groups/_contact.html.erb
<h2>Event Mail</h2>

<%= form_with  url: user_group_contact_path(user.id,group.id), method: :post, local: false do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class: "form-control " %>
  <p>Contact</p>
  <%= f.text_area :contact,class: "form-control " %>

  <%= f.submit "送信", class:"btn btn-info d-block mt-3" %>
<% end %>

app/views/groups/contact.html.erb
 <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <div id="after-send">
           <%= render 'contact',user: @user, group: @group %>
        </div>
      </div>
    </div>
</div>

app/views/groups/contact_create.js.erb
document.getElementById("after-send").innerHTML = "<%= j(render 'aftersend',title: @title, contact: @contact) %>"

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Edit Group</h2>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with model: @group, url: user_group_path, method: :patch, local: true do |f| %>
        <p>グループ名</p>
        <%= f.text_field :name, class: "form-control " %>
        <p>紹介文</p>
        <%= f.text_area :introduction,class: "form-control " %>
        <p>グループ画像</p>
        <%= f.file_field :image_id,accept: 'images/*' %>
        <%= f.submit "Update Group", class:"btn btn-info d-block mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <%= render 'layouts/errors', obj: @book %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-8 offset-1">
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <%= image_tag group.get_image_id("50x50") %>
              </td>
              <td><%= link_to group.name, user_group_path(current_user.id, group.id) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.group_users.count %></td>
                <% if group.owner_id == current_user.id %>
                  <td><%= link_to "Edit", edit_user_group_path(current_user.id,group.id),class:"btn btn-success" %></td>
                <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Create Group</h2>
      <%= form_with model: @group, url: user_groups_path, method: :post, local: true do |f| %>
        <p>グループ名</p>
        <%= f.text_field :name, class: "form-control " %>
        <p>紹介文</p>
        <%= f.text_area :introduction,class: "form-control " %>
        <p>グループ画像</p>
        <%= f.file_field :image_id,accept: 'images/*' %>
        <%= f.submit "Create Group", class:"btn btn-info d-block mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Group detail</h2>
      	<table class='table'>
      	  <thead>
            <tr>
              <th></th>
              <th>グループ名</th>
              <th>紹介文</th>
              <th>メンバー</th>
              <th colspan="2"></th>
            </tr>
          </thead>
      	  <tr>
          <td>
            <%= image_tag @group.get_image_id("100x100") %>
          </td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <ul class="list-inline">
              <% @group.group_users.each do |group_user| %>
                <li>
                  <%= group_user.user.name %>
                </li>
              <% end %>
            </ul>

          </td>
          <% if @group.owner_id == current_user.id %>
            <td><%= link_to 'Edit', edit_user_group_path(current_user.id,@group.id), class: "btn btn-sm btn-success " %></td>
            <td><%= link_to 'Notice an Event',user_group_contact_path(current_user.id,@group.id), class: "btn btn-info" %></td>
          <% else %>
            <% if @isgroup %>
             <td><%= link_to "Leave this group", user_group_out_path(current_user.id,@group.id),class:"btn btn-danger" %></td>
            <% else %>
             <td><%= link_to "join this group", user_group_join_path(current_user.id,@group.id),class:"btn btn-success" %></td>
            <% end %>
          <% end %>

        </tr>
      </table>

    </div>
  </div>
</div>
<%= @isgroup %>