config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  get '/searches/search' => 'searches#search',as: 'searches'
  get '/searches/categorysearch' => 'searches#categorysearch'

  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do

    resources :reviews, only: [:create]
    resources :book_comments, only: [:create,:destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      get 'join' => 'groups#join'
      get 'out' => 'groups#out'
      get 'contact' => 'groups#contact'
      post 'contact' => 'groups#contact_create'

    end
    get :followings, on: :member
    get :followers,on: :member
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comment
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :group_users, dependent: :destroy


  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name:"Relationship",foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  has_many :favorited_books, through: :favorites, source: :book

  has_one_attached :profile_image
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: {maximum: 50}




  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end

  def followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backword_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  
  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController


  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user),notice: 'guestuserでログインしました。'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit,:update]
  before_action :ensure_guest_user, only: [:edit]


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @category = @book.categories.new
    @currentuserentry = Entry.where(user_id: current_user.id)
    @userentry = Entry.where(user_id: @user.id)



    if @user.id != current_user.id

      @currentuserentry.each do |cu|
        @userentry.each do |u|

          if cu.room_id == u.room_id
            @isroom = true
            @roomid = cu.room_id
          end

        end
      end

      unless @isroom
        @room = Room.new
        @entry = Entry.new
      end

   end




    #bookrecord7b@record_today = @books.created_today
    #bookrecord7b@record_yesterday = @books.created_yesterday
    #bookrecord7b@record_day = @record_today.count / @record_yesterday.count.to_f
    #bookrecord7b@record_thisweek = @books.created_thisweek
    #bookrecord7b@record_lastweek = @books.created_lastweek
    #bookrecord7b@record_week = @record_thisweek.count / @record_lastweek.count.to_f

    #bookrecord8b@record_today = @books.created_today
    #bookrecord8b@record_1day = @books.created_1day
    #bookrecord8b@record_2day = @books.created_2day
    #bookrecord8b@record_3day = @books.created_3day
    #bookrecord8b@record_4day = @books.created_4day
    #bookrecord8b@record_5day = @books.created_5day
    #bookrecord8b@record_6day = @books.created_6day

    day =params[:day]
    @record_search = @books.where(['created_at LIKE ? ', "#{day}%"])

  end

  def index
    @users = User.all
    @book = Book.new
    @category = @book.categories.new
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user),notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookrecord.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">今日の投稿数</th>
      <th scope="col">前日の投稿数</th>
      <th scope="col">前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @record_today.count %></td>
      <td><%= @record_yesterday.count %></td>
      <% if @record_yesterday.count == 0 %>
         <td>前日無</td>
      <% else %>
         <td><%= (@record_day *100).round %>%</td>
      <% end %>

    </tr>
  </tbody>
</table>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">今週の投稿数</th>
      <th scope="col">前週の投稿数</th>
      <th scope="col">前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @record_thisweek.count %></td>
      <td><%= @record_lastweek.count %></td>
      <td>70%</td>
    </tr>
  </tbody>
</table>

app/views/users/_bookrecord7b.erb
<h3>投稿数の前日比・前週比</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">今日の投稿数</th>
      <th scope="col">前日の投稿数</th>
      <th scope="col">前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @record_today.count %></td>
      <td><%= @record_yesterday.count %></td>
      <% if @record_yesterday.count == 0 %>
         <td>前日無</td>
      <% else %>
         <td><%= (@record_day *100).round %>%</td>
      <% end %>

    </tr>
  </tbody>
</table>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">今週の投稿数</th>
      <th scope="col">前週の投稿数</th>
      <th scope="col">前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @record_thisweek.count %></td>
      <td><%= @record_lastweek.count %></td>
      <td>
        <% if @record_lastweek.count == 0 %>
          前週無
        <% else %>
          <%= @record_week * 100.round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/users/_bookrecord8b.html.erb
<h3>7日分の投稿数</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">6日前</th>
      <th scope="col">5日前</th>
      <th scope="col">4日前</th>
      <th scope="col">3日前</th>
      <th scope="col">2日前</th>
      <th scope="col">1日前</th>
      <th scope="col">今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @record_6day.count %></td>
      <td><%= @record_5day.count %></td>
      <td><%= @record_4day.count %></td>
      <td><%= @record_3day.count %></td>
      <td><%= @record_2day.count %></td>
      <td><%= @record_1day.count %></td>
      <td><%= @record_today.count %></td>
    </tr>
 </table>

 <canvas id="myChart"></canvas>

 <!-- ライブラリ読込 -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
 <script>
 var ctx = document.getElementById('myChart').getContext('2d');
 var chart = new Chart(ctx, {
     type: 'line',

     // データを指定
     data: {
         labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
         datasets: [{
             label: '投稿した本の数',
             borderColor: 'blue',
             fill: false,
             data: [<%= @record_6day.count %>, <%= @record_5day.count %>, <%= @record_4day.count %>, <%= @record_3day.count %>,<%= @record_2day.count %>, <%= @record_1day.count %>, <%= @record_today.count %>]
         }]
     },

     // 設定はoptionsに記述
     options: {
       //タイトル
       title: {
         display: true,
         text: '7日間の投稿数の比較'
       }
     }
});
</script>

app/views/users/_bookrecord9b.html.erb
<%= form_with url: user_path(current_user.id),method: :get, local: false do |f| %>
  <%= f.date_field :day %>
  <%= f.submit "検索",class:"btn btn-primary" %>
<% end %>

<div id="record_search">

</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image("50x50") %></td>
        <td><%= user.name %></td>
        <td><p>フォロー数：<%= user.followings.count %></p></td>
        <td><p>フォロワー数：<%= user.followers.count %></p></td>
        <td>
          <% if user != current_user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id),method: :delete%>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id),method: :post %>
            <% end %>
          <% end %>

        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image("100x100") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to followings_user_path(user.id) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
     <th>followers</th>
     <th>
      <%= link_to followers_user_path(user.id) do %>
       <%= user.followers.count %>
      <% end %>
     </th>

  </tr>
  <tr>
    <th>
      <% if user != current_user %>
        <% if user.followed_by?(current_user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id),method: :delete,class:"btn btn-danger"%>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id),method: :post,class:"btn btn-info" %>
        <% end %>
      <% end %>
    </th>
    <th>
      <% if user.id != current_user.id %>
        <% if (current_user.followed_by?(user)) && (user.followed_by?(current_user)) %>
          <% if isroom == true %>
            <%= link_to "chatを始める", room_path(roomid) %>
          <% else %>
            <%= form_with model: room, local: true do |f| %>
              <%= fields_for entry,local: true do |e| %>
                <%= e.hidden_field :user_id,value:"#{user.id}" %>
              <% end %>
              <%= f.submit "chatを始める" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </th>
  </tr>

</table>

<div class='row'>
  <% if @user.name == "guestuser" %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>

</div>

app/views/users/_record.html.erb
<h3>検索結果</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= record_search.count %>
      </td>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
           <%= image_tag user.get_profile_image("50x50") %>
        </td>
        <td><%= user.name %></td>
        <td><p>フォロー数：<%= user.followings.count %></p></td>
        <td><p>フォロワー数：<%= user.followers.count %></p></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/followings.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
           <%= image_tag user.get_profile_image("50x50") %>
        </td>
        <td><%= user.name %></td>
        <td><p>フォロー数：<%= user.followings.count %></p></td>
        <td><p>フォロワー数：<%= user.followers.count %></p></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_user_group_path(current_user.id) %>|<%= link_to "グループ一覧", user_groups_path(current_user) %>
      <div id="books">
        <%= render 'index',users: @users %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user,isroom: @isroom,room: @room, entry: @entry, roomid: @roomid %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div id="books">
        <%= render 'books/index',books: @books %>
      </div>

      <%= render 'bookrecord9b' %>
    </div>
  </div>
</div>

app/views/users/show.js.erb
document.getElementById('record_search').innerHTML = '<%= j(render 'record',record_search: @record_search) %>';