config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  get '/searches/search' => 'searches#search',as: 'searches'
  get '/searches/categorysearch' => 'searches#categorysearch'

  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do

    resources :reviews, only: [:create]
    resources :book_comments, only: [:create,:destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      get 'join' => 'groups#join'
      get 'out' => 'groups#out'
      get 'contact' => 'groups#contact'
      post 'contact' => 'groups#contact_create'

    end
    get :followings, on: :member
    get :followers,on: :member
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments
  has_many :favorited_users ,through: :favorites, source: :user
  has_many :categories, dependent: :destroy
  accepts_nested_attributes_for :categories, allow_destroy: true
  has_many :category_books, through: :categories, source: :book




  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  validates :rate, presence: true

  is_impressionable


  #bookrecord7bscope :created_today, -> {where(created_at: Time.zone.now.all_day)}
  #bookrecord7bscope :created_yesterday, -> {where(created_at: 1.day.ago.all_day)}
  #bookrecord7bscope :created_thisweek, -> {where(created_at: Date.today.prev_week(:saturday) .. Date.today-(Date.today.wday-5))}
  #bookrecord7bscope :created_lastweek, -> {where(created_at: Date.today-(Date.today.wday-6)-14 .. Date.today-(Date.today.wday-5)-7)}


  #bookrecord8bscope :created_today, -> {where(created_at: Time.zone.now.all_day)}
  #bookrecord8bscope :created_1day, -> {where(created_at: 1.day.ago.all_day)}
  #bookrecord8bscope :created_2day, -> {where(created_at: 2.day.ago.all_day)}
  #bookrecord8bscope :created_3day, -> {where(created_at: 3.day.ago.all_day)}
  #bookrecord8bscope :created_4day, -> {where(created_at: 4.day.ago.all_day)}
  #bookrecord8bscope :created_5day, -> {where(created_at: 5.day.ago.all_day)}
  #bookrecord8bscope :created_6day, -> {where(created_at: 6.day.ago.all_day)}

  scope :created_1week, -> {where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day)}




  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search,word)
    if search == "parfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backword_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user,only: [:edit, :update]
  impressionist :actions=> [:show]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @category = @book.categories.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    @user = @book.user
     @currentuserentry = Entry.where(user_id: current_user.id)
    @userentry = Entry.where(user_id: @user.id)
    impressionist(@book, nil, unique: [:session_hash.to_s])

    if @user.id != current_user.id

      @currentuserentry.each do |cu|
        @userentry.each do |u|

          if cu.room_id == u.room_id
            @isroom = true
            @roomid = cu.room_id
          end

        end
      end

      unless @isroom
        @room = Room.new
        @entry = Entry.new
      end

    end
  end

  def index
    if params[:sort_date] == "rate"
      @books = Book.all.order(rate: :desc)
    elsif params[:sort_date] == "create"
      @books = Book.all.order(created_at: :desc)
    else
      @books = Book.created_1week.sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}
    end

    @book =Book.new
    @category = @book.categories.new

  end




  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate,categories_attributes: [:name, :_destroy,])
  end

  def correct_user
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_categorybooks.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>category</th>
      <th colspan="3"></th>

    </tr>
  </thead>
  <tbody>
    <% categories.each do |category| %>
      <% book = Book.find(category.book_id) %>
      <tr>
        <td>

          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image("50x50") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
         <td>
          <%book.categories.each do |category| %>
            <p><%= category.name %></p>
          <% end %>
        </td>
        <td id='book_<%= book.id %>'>
          <%= render 'books/favorite',book: book %>
        </td>
        <td><p>コメント数：<%= book.book_comments.count %></p></td>

        <td>
           <div id="star-rate-<%= book.id %>"></div>
            <script>
                  $('#star-rate-<%= book.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    readOnly: true,
                    score: <%= book.rate %>,
                });
            </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_comment.html.erb
<% book_comments.each do |comment| %>
  <tr>
    <td>
      <%= link_to user_path(comment.user) do %>
        <%= image_tag comment.user.get_profile_image("50x50") %><br>
        <%= comment.user.name %>
      <% end %>
    </td>
    <td>
      <p class="text-center ml-4"><%= comment.comment %></p>
    </td>
    <td>
      <% if current_user.id == comment.user.id %>
        <%= link_to "Destroy", book_book_comment_path(comment.book,comment), method: :delete,remote: true, class:"btn btn-danger d-inline-block  ml-4 mb-3"%>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/books/_commentform.html.erb
<%= form_with model:[book,book_comment],local: false do |f| %>
  <%= f.text_area :comment,style: "width: 100%",id:"text_area" %>
  <%= f.submit "送信",class: " d-block"  %>
<% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorite_path(book.id),method: :delete, remote: true do %>
    ❤︎<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorite_path(book.id),method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.fields_for :categories do |c| %>
      <%= c.label :category %>
      <%= c.text_field :name,  class: 'form-control book_body' %>
    <% end %>
  </div>
  <div class="field" id="star">
    <%= f.label :rate, "星評価", id: "e" %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
   <script>
        $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            scoreName: 'book[rate]',
        });
    </script>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>category</th>
      <th colspan="3"></th>

    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image("50x50") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
         <td>
          <% book.categories.each do |category| %>
           <%= link_to category.name, searches_categorysearch_path(word: "#{category.name}"),remote: true %>
          <% end %>
        </td>
        <td id='book_<%= book.id %>'>
          <%= render 'books/favorite',book: book %>
        </td>
        <td><p>コメント数：<%= book.book_comments.count %></p></td>

        <td>
           <div id="star-rate-<%= book.id %>"></div>
            <script>
                  $('#star-rate-<%= book.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    readOnly: true,
                    score: <%= book.rate %>,
                });
            </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= form_with model: @book,local:true do |f| %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
       <div id="star-rate-<%= @book.id %>"></div>
            <script>
                  $('#star-rate-<%= @book.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    readOnly: true,
                    score: <%= @book.rate %>,
                });
            </script>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>

  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <%= render 'layouts/errors', obj: @book %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "評価の高い順", books_path(sort_date: "rate") %>|<%= link_to "新しい順",books_path(sort_date: "create") %>
      <div id="books">
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user,isroom: @isroom,room: @room, entry: @entry, roomid: @roomid %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image("100x100") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
           <td>
              <%@book.categories.each do |category| %>
                <p><%= category.name %></p>
              <% end %>
            </td>
          <td id="book_<%= @book.id %>">
            <%= render 'books/favorite', book: @book %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', "/books/#{@book.id}", method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
           <td>

          </td>
          <td id="comment_count">
            <p>コメント数：<%= @book.book_comments.count %></p>
          </td>
          <td>
            <div id="star-rate-<%= @book.id %>"></div>
            <script>
                  $('#star-rate-<%= @book.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    readOnly: true,
                    score: <%= @book.rate %>,
                });
            </script>
          </td>
        </tr>
      </table>
      <table id="book_comments">
        <%= render 'books/comment',book_comments: @book_comments %>
      </table>
      <div id="comment_form">
        <%= render 'books/commentform',book: @book,book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.js.erb
alert('いいねが押せている！');